### ISSUE TITLE
ci fails when a list of dataframes is passed

### ISSUE THREAD

**Issue by azvoleff** [xfim/ggmcmc#38]
The manual for `ci` implies a list of `data.frame`s can be passed to the function and confidence intervals calculated for each model (that https://github.com/xfim/ggmcmc/blob/master/R/functions.R#L95).

 When I try this I get:

    Error in UseMethod("group_by_") : 
      no applicable method for 'group_by_' applied to an object of class "list"

A glance at [the code](https://github.com/xfim/ggmcmc/blob/master/R/functions.R#L112) shows that `group_by` is run on the input to the function - this will always fail if a list is passed.

**Comment by xfim** [comment]
Thank you for noticing it, @azvoleff. You are right.

But at this point, I am not sure of what is the best way to proceed. I am tempted to delete from the manual the capacity to work directly with lists and leave this to users. I think that this is the most consistent behaviour considering the following:

* The idea is to work with tidy objects as much as possible. Using lists may not
facilitate this, although the output object can still be a tidy dataframe with a new column containing the name of the list.

* It keep things simple.

* It does not break anything in `ggs_caterpillar()`.

But if you think that this is a clear improvement I would consider implementing it.

What is your opinion?

**Comment by azvoleff** [comment]
I agree - best to keep things simple and consistent, and require a `data.frame` as input. I was going to suggest that allowing to also group by a `Model` column, if present would be helpful, but on second thought, probably best to just revise the docs to drop the implied support for lists. When calculating CIs for multiple models the user can always just use a `foreach` loop.

Thanks again for the great package!

**Comment by xfim** [comment]
Solved at commit 40789bf5c475cbf63ff12bc25eaed11a07d54feb.
