### ISSUE TITLE
ggs_caterpillar ignores thick_ci and thin_ci arguments

### ISSUE THREAD

**Issue by jonathan-g** [xfim/ggmcmc#50]
Calling ggs_caterpillar with values for thick_ci and thin_ci doesn't change the plot.

When I call `ggs_caterpillar(D)` and `ggs_caterpillar(D, thick_ci = c(0.4,0.6)`, I get identical plots. Using ggmcmc_0.7.3 from CRAN.

I get the same result when I install the github verson with `devtools::install_github('xfim/ggmcmc')`

**Comment by xfim** [comment]
Thank you, @jonathan-g for reporting the bug. It is an embarrassing one. It has been solved in commit  7ce00f0. The development version should be fine right now.
