### ISSUE TITLE
Make "ggs" understand "stanreg" objects in addition to "stanfit" (feature suggestion)

### ISSUE THREAD

**Issue by stefanherzog** [xfim/ggmcmc#52]
It would be great if `ggs` could import "stanreg" objects generated by the [rstanarm](https://cran.r-project.org/web/packages/rstanarm/) R package in addition to the generic "stanfit" objects. Thanks!

**Comment by xfim** [comment]
Sure, @stefanherzog . I will work on it. Thank you for the suggestion. I simply assumed that rstanarm objects were stanfit, without checking.

**Comment by stefanherzog** [comment]
@xfim : Thanks so much!

**Comment by xfim** [comment]
Solved at #b6bdf968e687045f7ad56127a937434c3da241cf.
Please, @stefanherzog, test it to check that it works under different circumstances.

**Comment by stefanherzog** [comment]
@xfim : Thanks!

While trying to test the new version (addressing #52 and #53), I couldn't install the latest version using

```
devtools::install_github("xfim/ggmcmc")
```

I got the following error:

```
Downloading GitHub repo xfim/ggmcmc@master
Installing ggmcmc
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/r8/s267648d7mq_1d37h1ts2bnd1348rw/T/RtmpJIbG5d/devtools6a8365759d68/xfim-ggmcmc-6db9525'  \
  --library='/Users/herzog/Library/R/3.2/library' --install-tests 

* installing *source* package ‘ggmcmc’ ...
** R
** data
** inst
** preparing package for lazy loading
Error : package ‘dplyr’ 0.4.3 was found, but > 0.4.3 is required by ‘ggmcmc’
ERROR: lazy loading failed for package ‘ggmcmc’
* removing ‘/Users/herzog/Library/R/3.2/library/ggmcmc’
* restoring previous ‘/Users/herzog/Library/R/3.2/library/ggmcmc’
Error: Command failed (1)
```

However, [dplyr 0.4.3 seems to be the latest release available](https://github.com/hadley/dplyr/releases).

Here's my session info

```
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.2 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3

loaded via a namespace (and not attached):
 [1] httr_1.0.0         assertthat_0.1     R6_2.1.2           magrittr_1.5       rsconnect_0.4.1.11 parallel_3.2.0     DBI_0.3.1         
 [8] tools_3.2.0        curl_0.9.5         Rcpp_0.12.4        memoise_0.2.1      stringi_1.0-1      knitr_1.12.3       stringr_1.0.0     
[15] digest_0.6.9       devtools_1.9.1   
```

**Comment by xfim** [comment]
Yes, this is a known situation. The issue is that the development version of ggmcmc relies on the development version of dplyr right now. I am waiting for dplyr to be stabilized (therefore, greater than the current 0.4.3) to stabilize ggmcmc as well. 

So now I have changed the requirement again to lower it, so that you can compile it, but please be sure that you use the dplyr version as well.
