### ISSUE TITLE
Make "ggs" understand "brmsfit" objects (feature suggestion) 

### ISSUE THREAD

**Issue by stefanherzog** [xfim/ggmcmc#53]
Hi!

It would be wonderful if `ggs` would understand `brmsfit` objects from the package [brms: Bayesian Regression Models using Stan](https://cran.r-project.org/web/packages/brms/index.html). There's a method [`as.mcmc.brmsfit`](http://finzi.psych.upenn.edu/library/brms/html/as.mcmc.brmsfit.html) that turns a `brmsfit` object into a list of MCMC samples ("Extract posterior samples for use with the coda package").

Thanks for considering this!

**Comment by xfim** [comment]
Solved also at #b6bdf968e687045f7ad56127a937434c3da241cf.
Please, @stefanherzog, test it to check that it works under different circumstances.
