### ISSUE TITLE
setting greek=T mixes up labels

### ISSUE THREAD

**Issue by jonathan-g** [xfim/ggmcmc#54]
When I call `ggs_caterpillar` with `greek=T`, the parsed labels appear on the chart in alphabetical order, not in the order of the medians of the distributions, so the bars on the chart get the wrong labels.

Calling `ggs_caterpillar(g)` and `ggs_caterpillar(g, greek=T)` the bars appear in the same places, but the labels appear in different order.
![not_greek](https://cloud.githubusercontent.com/assets/5304060/14938653/2bf6ad44-0ef0-11e6-9ae8-c72b393d67ad.png)
![greek](https://cloud.githubusercontent.com/assets/5304060/14938654/33bb1236-0ef0-11e6-9095-edef84b7fa52.png)

[g.zip](https://github.com/xfim/ggmcmc/files/243838/g.zip)

**Comment by xfim** [comment]
Thank you for reporting this, @jonathan-g, and for doing it is a reproducible way easy to debug.

It must be solved in commit 6db95256f.

Please, do not hesitate to open another issue for anything else that you may have (bug, question, documentation request, feature request, ideas for the future).
