### ISSUE TITLE
Disable/change sorting in ggs_catarpillar

### ISSUE THREAD

**Issue by lindeloev** [xfim/ggmcmc#60]
I make inference on a variable where there is a meaningful order to the indices. I would like to keep that order in the plot. Could you implement either (1) a method to disable value-sorting and keep the alphabetical sorting? or (2) an option to manually specify a sorting.

Here is the plot. In this case, I would just like them in the order of the index to see if discriminability covaries with item difficulty:
![image](https://user-images.githubusercontent.com/1439417/33322069-36a4b8ca-d448-11e7-8588-39cd6673bf79.png)

**Comment by xfim** [comment]
There is an argument in `ggs_caterpillar()`, `sort`, that is expected to do exactly this. Does it solve your issue?
