### ISSUE TITLE
Error with 0-var check in ggs_geweke from sde0f

### ISSUE THREAD

**Issue by brianstock** [xfim/ggmcmc#64]
Hello,

I just submitted a pull request with a fix, but posting an issue as well. When using your `ggmcmc` package to look at diagnostics for a JAGS model, I encountered an error at line 40 of `ggs_geweke`:

```
> D.geweke <- D.geweke %>%
+     dplyr::group_by (Parameter, Chain, part) %>%
+     dplyr::summarize(m=mean(value), sde0f=sde0f(value), n=n())
Error in summarise_impl(.data, dots) : 
  Evaluation error: zero-variance series.
```

Traced this to the check for 0 variance in `sde0f` and believe my pull request fixes the issue: https://github.com/xfim/ggmcmc/pull/63

**Comment by xfim** [comment]
Closed by PR #63
