### ISSUE TITLE
Keeping order of parameters 

### ISSUE THREAD

**Issue by haziqj** [xfim/ggmcmc#68]
Hi, I have a feature request. I would like to keep the order of parameters the same as it is from the output of the `mcmc.list`. I mostly use `runjags` package, so the `summary()` output of a `runjags` object will typically be in the order I set it in the `monitor` argument of `run.jags()`.

E.g. The plots from the runjags model `mod <- run.jags(..., monitor = c("gamma", "beta" ))` will sort the parameters in alphabetical order, so it will appear as `beta[1], beta[2],..., gamma[1], gamma[2],...` etc.

I understand there is the `sort=FALSE` option in `ggs()` function, but this doesn't seem to be doing what I'd like it to.

One quick and lazy way that I found to work was to edit the lines in `ggs.R` where it says `D$Parameter <- factor(D$Parameter)` to `D$Parameter <- factor(D$Parameter, levels = unique(D$Parameter))`, in particular under the if statement for `sort`. This then allows me to run `ggs()` function with `sort = FALSE`, and it will give me plots exactly in the order as it appears from the `runjags` output.

The only thing is I don't know if this breaks the `sort = FALSE` functionality that you originally intended. I can't seem to figure out what this does?

Hope I was clear. Thanks for a great package!

**Comment by xfim** [comment]
Thank you, @haziqj , for your kind words.

`sort` is an argument to keep the order of parameters (internally, in the factors), when there are things like "theta[1]", "theta[2]", "theta[10]", "theta[10001]". In that case, following R's logic the order would be  "theta[1]", "theta[10]", "theta[10001]" and finally "theta[2]". But that is not usually what we want. Therefore, I made the default `sort = TRUE` that sorts them by family (first) and then by "number", not by "character" order.

Does this clarify it?

Your request makes total sense and should be relatively easy to implement. But it will require another argument, to avoid misunderstandings with the current "sort". Let me check.

**Comment by haziqj** [comment]
Ah yes, that clarifies it. I did see this behaviour for `sort=FALSE` but I guess I couldn't imagine how this might be useful 😅

Awesome, thanks for considering this.

**Comment by xfim** [comment]
Let me know if this commit works: d8a0d5139a1922ff40b6e87e82ef8f23705e7e29

I have included a new parameter "keep_original_order".
